// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_2OlRYDxvPkWuWWsBi867vkz-R4Egq9o',
    appId: '1:31216335582:web:dca53c4b2926278350204f',
    messagingSenderId: '31216335582',
    projectId: 'studymate-8fca7',
    authDomain: 'studymate-8fca7.firebaseapp.com',
    storageBucket: 'studymate-8fca7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnMO1LHJiS-F6Vb1skaK6RAtoPqNiv2g',
    appId: '1:31216335582:android:101a9548fc7dc2d950204f',
    messagingSenderId: '31216335582',
    projectId: 'studymate-8fca7',
    storageBucket: 'studymate-8fca7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiL9Ad6gpNS3fotsX5bkGsdqwWgB-3udA',
    appId: '1:31216335582:ios:0019431a7a9f00dc50204f',
    messagingSenderId: '31216335582',
    projectId: 'studymate-8fca7',
    storageBucket: 'studymate-8fca7.firebasestorage.app',
    iosBundleId: 'com.example.ucTask1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiL9Ad6gpNS3fotsX5bkGsdqwWgB-3udA',
    appId: '1:31216335582:ios:0019431a7a9f00dc50204f',
    messagingSenderId: '31216335582',
    projectId: 'studymate-8fca7',
    storageBucket: 'studymate-8fca7.firebasestorage.app',
    iosBundleId: 'com.example.ucTask1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_2OlRYDxvPkWuWWsBi867vkz-R4Egq9o',
    appId: '1:31216335582:web:f0469f51cdd0614950204f',
    messagingSenderId: '31216335582',
    projectId: 'studymate-8fca7',
    authDomain: 'studymate-8fca7.firebaseapp.com',
    storageBucket: 'studymate-8fca7.firebasestorage.app',
  );
}
